Repository vskurikhin/otus-highload-architect-2021-03-VSkurikhin, pull requests merged in 2021-04, with the labels that each got.

#1 Homework/1
  .gitignore
  README.md
  app/config/config.go
  doc/homeworks.md
  doc/lectures.md
  doc/other.md
  go.mod
Labels: enhancement

#2 Добавлен server.go.
  app/server/server.go
  go.mod
Labels: enhancement

#3 Поправлен файл main.yml в GitHub workflows
  .github/workflows/main.yml
  go.sum
  main.go
Labels: enhancement

#5 Добавлен файл inject_server.go.
  cmd/inject_server.go
  go.mod
  go.sum
Labels: enhancement

#6 Добавлены файлы application.go, wire.go, сгенерирован wire_gen.go.
  cmd/application.go
  cmd/wire.go
  cmd/wire_gen.go
  go.sum
  main.go
Labels: enhancement

#7 Добавлен файл init_logging.go.
  cmd/init_logging.go
  main.go
Labels: enhancement

#8 Добавлены файлы index.go и root.go.
  app/handlers/root/home/index.go
  app/handlers/root/root.go
  cmd/inject_server.go
  main.go
Labels: enhancement

#9 Homework/1 fasthttp routing savsgio atreugo
  .gitignore
  README.md
  app/config/config.go
  app/handlers/root/home/index.go
  app/handlers/root/root.go
  app/jwt/auth_check_token.go
  app/jwt/jwt.go
  app/server/server.go
  cmd/application.go
  cmd/init_logging.go
  cmd/inject_server.go
  cmd/wire.go
  cmd/wire_gen.go
  go.mod
  go.sum
  main.go
Labels: enhancement

#10 Рефакторинг main.go.
  app/config/consts.go
  app/jwt/auth_check_token.go
  app/server/handlers/handlers.go
  app/server/handlers/root.go
  main.go
Labels: enhancement

#11 Рефакторинг auth_check_token.go, root.go и main.go.
  app/jwt/auth_check_token.go
  app/message/api_message.go
  app/server/handlers/login.go
  app/server/handlers/root.go
  main.go
Labels: enhancement

#12 Homework/1 goose mysql 1
  README.md
  db/create/create.sql
  db/migrations/20210406130459_create_users_table.sql
  go.sum
Labels: enhancement

#13 Рефакторинг main.go и server.go.
  app/config/config.go
  app/model/login.go
  app/model/user.go
  app/server/handlers/api_user.go
  app/server/server.go
  db/migrations/20210406130459_create_users_table.sql
  go.mod
  go.sum
  main.go
Labels: enhancement

#14 Подключен React.
  .gitignore
  README.md
  app/jwt/auth_check_token.go
  app/server/handlers/root.go
  app/server/server.go
  doc/homeworks.md
  main.go
  web/.babelrc
  web/.gitignore
  web/README.md
  web/package-lock.json
  web/package.json
  web/public/favicon.ico
  web/public/generated/0.app-bundle.js
  web/public/generated/0.app-bundle.js.map
  web/public/generated/app-bundle.js
  web/public/generated/app-bundle.js.map
  web/public/index.html
  web/public/logo192.png
  web/public/logo512.png
  web/public/manifest.json
  web/public/robots.txt
  web/src/App.css
  web/src/App.jsx
  web/src/App.test.jsx
  web/src/index.css
  web/src/index.jsx
  web/src/logo.svg
  web/src/setupTests.js
  web/webpack.config.js
Labels: enhancement

#15 Рефакторинг api_message.go, App.jsx, index.jsx и login.go.
  README.md
  app/message/api_message.go
  app/message/token.go
  app/server/handlers/login.go
  web/package-lock.json
  web/package.json
  web/public/generated/app-bundle.js
  web/public/generated/app-bundle.js.map
  web/src/App.css
  web/src/App.jsx
  web/src/components/Dashboard/Dashboard.jsx
  web/src/components/Login/Login.css
  web/src/components/Login/Login.jsx
  web/src/components/Preferences/Preferences.jsx
  web/src/components/Signin/Signin.css
  web/src/components/Signin/Signin.jsx
  web/src/index.jsx
Labels: enhancement

#16 Редизайн БД добавленны таблицы login, user, interest и связь много ко…
  db/create/create.sql
  db/migrations/20210407102810_create_login_table.sql
  db/migrations/20210407103127_create_user_table.sql
  db/migrations/20210407103200_alter_user_foreign_keys.sql
  db/migrations/20210407103246_create_interest_table.sql
  db/migrations/20210407103428_create_user_has_interest_link_table.sql
  db/migrations/20210407103847_alter_user_has_interest_foreign_keys.sql
Labels: enhancement

#17 Редизайн БД добавлены таблицы login, user, interest и связь много ко…
  .babelrc
  .gitignore
  README.md
  app/dao/dao.go
  app/dao/interest.go
  app/dao/login.go
  app/dao/user.go
  app/jwt/auth_check_token.go
  app/model/interest.go
  app/model/login.go
  app/model/signin.go
  app/security/password.go
  app/security/password_test.go
  app/server/handlers/api_user.go
  app/server/handlers/login.go
  app/server/server.go
  db/migrations/20210407102999_alter_table_login_unique_username.sql
  db/migrations/20210407103127_create_user_table.sql
  db/migrations/20210407103246_create_interest_table.sql
  db/migrations/20210407103300_alter_table_interest_unique_interests.sql
  db/migrations/20210407103428_create_user_has_interests_link_table.sql
  db/migrations/20210407103847_alter_user_has_interest_foreign_keys.sql
  db/migrations/20210407111710_insert_root_into_login_user.sql
  db/migrations/20210407140216_inserts_interest.sql
  db/migrations/20210407140318_link_user_has_interests.sql
  go.mod
  main.go
  package.json
  web/App.css
  web/App.jsx
  web/App.test.jsx
  web/components/Dashboard/Dashboard.jsx
  web/components/Login/Login.css
  web/components/Login/Login.jsx
  web/components/Signin/Signin.css
  web/components/Signin/Signin.jsx
  web/index.css
  web/index.jsx
  web/logo.svg
  web/package-lock.json
  web/public/css/input.css
  web/public/css/my-div-table.css
  web/public/css/p.css
  web/public/generated/app-bundle.js
  web/public/generated/app-bundle.js.map
  web/public/index.html
  web/setupTests.js
  web/src/components/Login/Login.css
  web/src/components/Login/Login.jsx
  web/src/components/Preferences/Preferences.jsx
  web/src/components/Signin/Signin.css
  web/src/components/Signin/Signin.jsx
  webpack.config.js
Labels: enhancement

#18 Homework/1 refactoring
  README.md
  app/dao/interest.go
  app/dao/user.go
  app/dao/user_has_interests.go
  app/server/handlers/api_user.go
  app/set/operations.go
  go.mod
  go.sum
  package.json
  web/components/Dashboard/Dashboard.jsx
  web/components/Login/Login.jsx
  web/components/Signin/Signin.jsx
  web/components/TableOfUsers/TableOfUsers.jsx
  web/consts.js
  web/public/css/input.css
  web/public/css/my-p.css
  web/public/css/semantic.min.css
  web/public/generated/app-bundle.js
  web/public/generated/app-bundle.js.map
  web/public/index.html
Labels: enhancement

#19 Рефакторинг пакетов backend dao и model объеденены в domain.
  app/dao/user.go
  app/domain/api_message.go
  app/domain/dao.go
  app/domain/interest.go
  app/domain/login.go
  app/domain/signin.go
  app/domain/token.go
  app/domain/user.go
  app/domain/user_has_interests.go
  app/model/interest.go
  app/model/login.go
  app/model/user.go
  app/security/auth_check_token.go
  app/security/jwt.go
  app/security/password.go
  app/server/handlers/api_user.go
  app/server/handlers/login.go
  app/server/server.go
Labels: enhancement

#20 Рефакторинг пакетов backend dao и model объеденены в domain.
  app/domain/signin.go
  app/domain/user.go
  app/security/check_values.go
  app/server/handlers/api_user.go
  app/server/handlers/login.go
  main.go
  web/App.jsx
  web/components/Login/Login.jsx
  web/components/Menu/AppMenu.jsx
  web/components/Signin/Signin.jsx
  web/components/TableOfUsers/TableOfUsers.jsx
  web/components/UserDefails/UserDefails.jsx
  web/components/UserForm/UserForm.jsx
  web/components/UserList/UserList.jsx
  web/public/generated/app-bundle.js
  web/public/generated/app-bundle.js.map
Labels: enhancement

#22 Homework/1
  app/config/config.go
  app/config/consts.go
  db/migrations/20210407111710_insert_root_into_login_user.sql
  web/public/css/themes/default/assets/fonts/brand-icons.eot
  web/public/css/themes/default/assets/fonts/brand-icons.svg
  web/public/css/themes/default/assets/fonts/brand-icons.ttf
  web/public/css/themes/default/assets/fonts/brand-icons.woff
  web/public/css/themes/default/assets/fonts/brand-icons.woff2
  web/public/css/themes/default/assets/fonts/icons.eot
  web/public/css/themes/default/assets/fonts/icons.otf
  web/public/css/themes/default/assets/fonts/icons.svg
  web/public/css/themes/default/assets/fonts/icons.ttf
  web/public/css/themes/default/assets/fonts/icons.woff
  web/public/css/themes/default/assets/fonts/icons.woff2
  web/public/css/themes/default/assets/fonts/outline-icons.eot
  web/public/css/themes/default/assets/fonts/outline-icons.svg
  web/public/css/themes/default/assets/fonts/outline-icons.ttf
  web/public/css/themes/default/assets/fonts/outline-icons.woff
  web/public/css/themes/default/assets/fonts/outline-icons.woff2
  web/public/css/themes/default/assets/images/flags.png
Labels: enhancement

#26 Update lectures.md
  doc/lectures.md
Labels: documentation

#27 Введение в высокие нагрузки - lectures.md
  doc/lectures.md
Labels: documentation

#28 Введение в высокие нагрузки - README.md
  README.md
Labels: documentation

#29 Индексы (часть 1) - doc/lectures.md
  README.md
  doc/lectures.md
Labels: documentation

#30 Update lectures.md
  doc/lectures.md
Labels: documentation

#31 Update lectures.md
  doc/lectures.md
Labels: documentation

#32 Lecture/3
  doc/lectures.md
Labels: documentation

#33 БД добавлена таблица user_has_friends связь много ко многим user - мо…
  app/domain/dao.go
  app/domain/user.go
  app/domain/user_has_friends.go
  app/server/handlers/api_user.go
  db/migrations/20210419163432_create_user_has_friends_link_table.sql
  db/migrations/20210419163438_alter_user_has_friends_foreign_keys.sql
  go.mod
  go.sum
Labels: enhancement

#34 Рефакторинг webpack.config.js. Настройки babel пуренесены в package.j…
  .babelrc
  app/domain/profile.go
  app/domain/session.go
  app/domain/user.go
  app/domain/user_has_friends.go
  app/server/handlers/api_user.go
  app/server/handlers/profile.go
  main.go
  package.json
  web/components/UserDefails/UserDetails.jsx
  web/components/UserForm/UserForm.jsx
  web/components/UserInterests/UserInterests.jsx
  web/redux/currentUser.js
  webpack.config.js
Labels: enhancement

#35 Исправлены SQL запросы с JOIN-ми в user.go.
  app/domain/user.go
Labels: enhancement

#36 Проработана обработка ошибок на стороне UI.
  app/domain/session.go
  app/security/check_values.go
  app/server/handlers/login.go
  web/App.jsx
  web/components/Error/Error.jsx
  web/components/Modal/Modal.jsx
  web/components/Modal/modal.css
  web/components/Signin/Signin.jsx
  web/public/css/index.css
  web/public/css/index.sh
  web/public/css/my-modal.css
  web/public/index.html
Labels: enhancement

#37 Homework/1 fix 1 1
  app/security/check_values.go
  app/server/handlers/api_user.go
  webpack.config.js
Labels: enhancement

#38 Рефакторинг меню, добавлен AppMenu.jsx.
  app/domain/interest.go
  app/domain/login.go
  app/domain/user.go
  app/security/jwt.go
  app/server/handlers/api_user.go
  app/server/handlers/login.go
  main.go
  web/App.jsx
  web/components/AppMenu/AppMenu.jsx
  web/components/Login/Login.jsx
  web/components/Menu/AppMenu.jsx
  web/components/MyProfile/MyProfile.jsx
  web/components/Signin/Signin.jsx
  web/components/TableOfUsers/TableOfUsers.jsx
  web/components/UserDefails/UserDetails.jsx
  web/components/UserForm/UserForm.jsx
  web/components/UserInterests/UserInterests.jsx
  web/components/UserList/UserList.jsx
  web/redux/currentUser.js
  webpack.config.js
Labels: enhancement

#39 Рефакторинг API по пользователям.
  app/domain/interest.go
  app/domain/user_has_friends.go
  app/domain/user_has_interests.go
  app/server/handlers/api_user.go
  app/server/handlers/api_user_friend.go
  app/server/handlers/api_user_list.go
  app/server/handlers/api_user_save.go
  app/server/handlers/api_user_signin.go
Labels: enhancement

#40 Master
  app/domain/interest.go
  app/domain/login.go
  app/domain/user.go
  app/domain/user_has_friends.go
  app/domain/user_has_interests.go
  app/security/jwt.go
  app/server/handlers/api_user.go
  app/server/handlers/api_user_friend.go
  app/server/handlers/api_user_list.go
  app/server/handlers/api_user_save.go
  app/server/handlers/api_user_signin.go
  app/server/handlers/login.go
  main.go
  web/App.jsx
  web/components/AppMenu/AppMenu.jsx
  web/components/Login/Login.jsx
  web/components/Menu/AppMenu.jsx
  web/components/MyProfile/MyProfile.jsx
  web/components/Signin/Signin.jsx
  web/components/TableOfUsers/TableOfUsers.jsx
  web/components/UserDefails/UserDetails.jsx
  web/components/UserForm/UserForm.jsx
  web/components/UserInterests/UserInterests.jsx
  web/components/UserList/UserList.jsx
  web/public/generated/app-bundle.js
  web/redux/currentUser.js
Labels: enhancement

#42 Исправлена ошибка UI при отображении данных о поле на персональной ст…
  web/components/UserDefails/UserDetails.jsx
Labels: bug
